<?php

namespace app\modules\orhidLegends\models;

use Yii;
use yii\web\UploadedFile;

use yii\helpers\FileHelper;
use yii\imagine\Image;
use yii\helpers\Json;
use Imagine\Image\Box;
use Imagine\Image\Point;
use karpoff\icrop\CropImageUploadBehavior;

/**
 * This is the model class for table "orhid_legends".
 *
 * @property integer $id
 * @property string $title
 * @property string $text
 * @property string $image
 * @property integer $language
 * @property integer $state
 */
class OrhidLegends extends \yii\db\ActiveRecord
{
    public $string;
    public $imageTmp;
    public $coverTmp;
    public $filename;
  public $image;
  public $crop_info;
    /**
     * @inheritdoc
     */
  public function __construct($search=null, $config = [])
  {
    if ($search == 'init'){
      $this->language = 0;
      $this->state = 0;
      $this->text = "Text";
      $this->title = "Title";
      $this->save();
      $this->text = "";
      $this->title = "";
    }
    parent::__construct($config);
  }
  public static function tableName()
    {
        return 'orhid_legends';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'text', 'language', 'state'], 'required'],
            [['language', 'state'], 'integer'],
            [['title'], 'string', 'max' => 64],
            [['text'], 'string'],
      //      [['image','cover'], 'file'],
            ['crop_info', 'safe'],
            ['cover', 'file', 'extensions' => 'jpeg', 'on' => ['insert']],
            [['cover'], 'image',
              'minHeight' => 500,
              'maxSize'=>3*1024*1024,
              'skipOnEmpty' => true
            ],
        ];
    }
    function behaviors()
    {
      return [
        [
          'class' => CropImageUploadBehavior::className(),
          'attribute' => 'cover',
          'scenarios' => ['insert', 'update'],
          'path' => '@webroot',
          'url' => '@web',
          'ratio' => 230/285,
        ],
      ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'text' => 'Text',
            'image' => 'Image',
            'cover' => 'Cover',
            'language' => 'Language',
            'state' => 'State',
        ];
    }

    public function beforeSave($insert){
      if (($this->title != "Title") && ($this->text != "Text")) {
        $this->coverTmp = UploadedFile::getInstance($this, 'cover');
        if ($this->coverTmp){
          $this->cover = 'img/orhidlegends/covers/' . substr(uniqid('img'),0,12) . '.' . $this->coverTmp->extension;
        }
      }
      return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

  public function afterSave($insert, $changedAttributes)
  {
    if (($this->title != "Title") && ($this->text != "Text")) {
      $photo = \yii\web\UploadedFile::getInstance($this, 'cover');

      if ($photo) {
        $path = 'img/orhidlegends/covers/';// Путь для сохранения
        if (!file_exists($path)) {
          mkdir($path, 0777, true);   // Создаем директорию при отсутствии
        }

        $request = Yii::$app->request;
        $post = $request->post();

        $class = $this::className();
        $class = str_replace('\\', '/', $class);
        $class = explode('/', $class);
        $class = $class[count($class) - 1];
        $cropParam = array();
        if (isset($post[$class])) {
          $cropParam = explode('-', $post[$class]['cover']);
        }

        if (count($cropParam) != 4) {
          $cropParam = array(0, 0, 100, 100);
        }
        $image = Image::getImagine()->open($photo->tempName);
        $img = (new Image($photo->tempName));

        $imgWidth = $image->getSize()->getWidth();
        $imgHeight = $image->getSize()->getHeight();

        $cropParam[0] = (int)($cropParam[0] * $imgWidth / 100);
        $cropParam[1] = (int)($cropParam[1] * $imgHeight / 100);
        $cropParam[2] = (int)($cropParam[2] * $imgWidth / 100);
        $cropParam[3] = (int)($cropParam[3] * $imgHeight / 100);

        $img->crop($photo->tempName, $cropParam[2] - $cropParam[0], $cropParam[3] - $cropParam[1], [$cropParam[0], $cropParam[1]])
          ->save($this->cover);
      }
    }
  }
}
